// AUTO-GENERATED from useLauncher return + provide() block + component usages
import { type Ref, type ComputedRef, type ShallowRef, inject, type InjectionKey } from "vue";
import type {
  Accounts, AdminPack, AdminUser, CollaboratorPublic, PackDetail,
  PackNewsPublic, PackCatalog, PackVersionPublic, CommentWithReplies,
  CrashAnalysis, MsDeviceCodeInfo, DuplicatesResult, JavaInfo, LicenseInfo,
  SkinInfo, LaunchLogEntry, MonoProfile, SavedServer, NewsItem, ScreenshotInfo,
  PackDescriptor, ProfileDetail, ScanResult, UserSession, AppStatus, SystemInfo,
  UpdateInfo, VerifyResult, VersionsInfo, ModUpdate, AccountEntry, SavedServersList,
  ScreenshotList, DuplicateGroup, DuplicateFile, ServerStatus, GameFileEntry,
  CurseSearchHit, CurseProjectDetail, PackInfo, CustomFile, DownloadProgress,
  InstalledVersion, TrackedMod, ExportSourceItem, BoostyAuth, McVersionInfo,
  ProfilePublic, UserPackSummary, UserCommentSummary, MonoUserPublic,
  AdminComment, AdminCreateUser, SuspectedMod, ModrinthProject, ModrinthVersion,
  ModrinthFile, ModrinthTags, AuthorServer, AuthorSocial, AuthorTheme,
  AuthorPackConfig, MonoPackPublic, UpdatePackRequest, ModrinthGalleryItem,
  ModrinthDependency, CommentPublic, CurseCategory, CursePackFile, CurseFile,
  CurseInstallResult, GameFileIcon, GameExited, BoostyAuth as BoostyAuthType,
} from "~/lib/types";
import type { GameFolderKind, ModrinthSearchKind } from "~/lib/bridge";

export interface LauncherCtx {
  AUTHOR_MAX_SERVERS: any;
  AUTHOR_MAX_SOCIALS: any;
  CREATE_LOADERS: any;
  PACK_CATS: any;
  PACK_CAT_LABELS: any;
  SIDEBAR_COLLAPSE: any;
  SIDEBAR_ICON: any;
  accountBusy: Ref<any>;
  accounts: Ref<Accounts>;
  activeBanner: any;
  activeLocaleAuthor: any;
  activeLocaleVersion: any;
  activePack: ComputedRef<any>;
  activePackRepo: any;
  addAuthorNews: (...args: any[]) => any;
  addAuthorServer: any;
  addAuthorShot: any;
  addAuthorSocial: any;
  addCollaborator: (...args: any[]) => any;
  addMonoPack: any;
  addPack: any;
  addingPack: Ref<any>;
  adminBanUser: (...args: any[]) => any;
  adminBusy: Ref<any>;
  adminDeleteComment: (...args: any[]) => any;
  adminDeletePack: (...args: any[]) => any;
  adminDeleteUser: (...args: any[]) => any;
  adminPacks: Ref<AdminPack[]>;
  adminSetRole: (...args: any[]) => any;
  adminUnbanUser: (...args: any[]) => any;
  adminUsers: Ref<AdminUser[]>;
  appClose: any;
  appMinimize: any;
  appToggleMaximize: any;
  appUpdate: Ref<{ version: string; notes: string } | null>;
  appUpdateProgress: Ref<number | null>;
  appUpdating: Ref<any>;
  applyAuthorAccent: any;
  applyAuthorAccentColor: any;
  applyBoostyGlobalAuth: (...args: any[]) => any;
  applyLocalSkin: (...args: any[]) => any;
  armAuthorDelete: any;
  authorAccent: any;
  authorAuthor: any;
  authorBanner: any;
  authorBoosty: any;
  authorBusy: Ref<any>;
  authorCollaborators: Ref<CollaboratorPublic[]>;
  authorDelArm: any;
  authorDesc: any;
  authorDetail: Ref<PackDetail | null>;
  authorDirty: any;
  authorFormBase: any;
  authorIcon: any;
  authorImportFile: any;
  authorImportMode: any;
  authorMinRam: any;
  authorMinRamMb: any;
  authorName: any;
  authorNewBody: any;
  authorNewChangelog: any;
  authorNewTitle: any;
  authorNewVersion: any;
  authorNews: Ref<PackNewsPublic[]>;
  authorNewsKind: Ref<"post" | "update">;
  authorOverviewBanner: any;
  authorPacks: Ref<PackCatalog[]>;
  authorSelected: Ref<string | null>;
  authorServers: any;
  authorShotCaption: any;
  authorShotUrl: any;
  authorShots: any;
  authorSocials: any;
  authorTab: Ref<"overview" | "versions" | "news" | "collabs" | "comments">;
  authorTheme: any;
  authorThemeFields: any;
  authorVersionFile: any;
  authorVersions: Ref<PackVersionPublic[]>;
  autostartOn: any;
  bannerOk: any;
  boostyAuthOpen: Ref<any>;
  boostyBusy: any;
  boostyError: any;
  boostyGlobalLinkedState: Ref<any>;
  boostyGlobalOpen: Ref<any>;
  boostyKey: any;
  boostySecret: any;
  boostyTargetPack: Ref<string | null>;
  boostyToken: any;
  bugBody: Ref<any>;
  bugCopied: Ref<any>;
  bugLog: Ref<any>;
  bugReportOpen: Ref<any>;
  busy: Ref<any>;
  cancelAuthorDelete: any;
  cancelBoostyLogin: (...args: any[]) => any;
  cap: any;
  catalogCommentCount: ComputedRef<any>;
  catalogComments: Ref<CommentWithReplies[]>;
  catalogCommentsBusy: Ref<any>;
  catalogDetail: Ref<PackDetail | null>;
  catalogDetailBusy: Ref<any>;
  catalogDetailTab: Ref<"description" | "screenshots" | "versions" | "news" | "comments">;
  catalogSource: any;
  categoryOptions: any;
  changelogLines: any;
  chooseCreateLoaderVersion: any;
  chooseCreateVersion: any;
  chooseEditVerLoaderVersion: any;
  chooseEditVerMc: any;
  clearFileSelection: (...args: any[]) => any;
  clearFileSort: any;
  clearSelAll: any;
  closeAuthorDetail: (...args: any[]) => any;
  closeBugReport: (...args: any[]) => any;
  closeCatalogDetail: (...args: any[]) => any;
  closeCrashAnalysis: (...args: any[]) => any;
  closeFileDetailWin: any;
  closeLibMenu: any;
  closeProfileView: (...args: any[]) => any;
  closeSearch: any;
  closeToTray: any;
  collabBusy: Ref<any>;
  collabName: any;
  collabPerms: any;
  commentDraft: any;
  commentEditDraft: any;
  commentEditId: any;
  commentReplyDraft: any;
  commentReplyTo: any;
  confirmUnbindPack: any;
  convertFileSrc: any;
  copyAuthorLink: any;
  copyBugReport: (...args: any[]) => any;
  copyCrashAnalysis: any;
  copyInviteLink: any;
  copyPackDeepLink: any;
  copyServerIp: any;
  cpBusy: any;
  cpCatOptions: any;
  cpCatSel: any;
  cpDetail: any;
  cpDetailLoading: any;
  cpErr: any;
  cpFiles: any;
  cpLoading: any;
  cpProject: any;
  cpResults: any;
  cpSearched: any;
  cpSortSel: any;
  cpTab: any;
  cpTabs: any;
  cpVerSel: any;
  crashAnalysis: Ref<CrashAnalysis | null>;
  crashView: any;
  createAuthorVersion: (...args: any[]) => any;
  createLibCat: any;
  createPack: any;
  createPackBanner: any;
  createPackBusy: any;
  createPackIcon: any;
  createPackLoader: any;
  createPackLoaderLvOpen: any;
  createPackLoaderVersion: any;
  createPackLoaderVersions: any;
  createPackLvBox: any;
  createPackMc: any;
  createPackName: any;
  createPackOpen: any;
  createPackVersionBox: any;
  createPackVersionOpen: any;
  createPackVersionQuery: any;
  createVersionGroups: any;
  curseCatOptions: any;
  curseCatSel: any;
  curseErr: any;
  curseInstallBusy: any;
  curseKeyOk: any;
  curseLoaderOptions: any;
  curseLoaderSel: any;
  curseLoading: any;
  curseMetaFor: any;
  curseResults: any;
  curseSearched: any;
  curseSortOptions: any;
  curseSortSel: any;
  curseVerSel: any;
  customBannerClass: any;
  customBannerNoteClass: any;
  customBannerState: any;
  customLibSections: any;
  customModsOpen: any;
  customScanBusy: Ref<any>;
  deepLinkExample: any;
  deleteAuthorNews: (...args: any[]) => any;
  deleteAuthorPack: (...args: any[]) => any;
  deleteAuthorScreenshot: (...args: any[]) => any;
  deleteAuthorVersion: (...args: any[]) => any;
  deleteLibCat: any;
  deleteSelectedFiles: any;
  deviceFlow: ComputedRef<MsDeviceCodeInfo | null>;
  discordRp: Ref<any>;
  dismissNotification: (...args: any[]) => any;
  doAuthorExport: any;
  doAuthorImport: any;
  doBoostyAuth: any;
  doExport: any;
  doLogin: any;
  doSearch: any;
  downloadJava: (...args: any[]) => any;
  downloadSelectedCurse: any;
  downloadSelectedMods: any;
  dragMrpack: any;
  dragSearchWin: any;
  duplicates: Ref<DuplicatesResult>;
  duplicatesLoading: Ref<any>;
  editCatalogComment: (...args: any[]) => any;
  editVerBusy: any;
  editVerLoader: any;
  editVerLoaderVersions: any;
  editVerLv: any;
  editVerLvBox: any;
  editVerLvOpen: any;
  editVerMc: any;
  editVerMcBox: any;
  editVerMcList: any;
  editVerMcOpen: any;
  editVerMcQuery: any;
  editVerName: any;
  editVerOpen: any;
  elyFlow: Ref<MsDeviceCodeInfo | null>;
  elyPolling: Ref<any>;
  enabledCountIn: (...args: any[]) => any;
  endSidebarDrag: any;
  envOptions: any;
  examplePackJson: any;
  exportAllChecked: any;
  exportBusy: any;
  exportExpanded: any;
  exportFormat: any;
  exportItems: any;
  exportLoading: any;
  exportMenuOpen: any;
  exportMenuRef: any;
  exportName: any;
  exportOpen: any;
  exportSelected: any;
  exportSelectedCount: any;
  exportUpload: any;
  exportVersionNum: any;
  exportVisibleRows: any;
  fileDeleteArmed: any;
  fileDeleteBusy: any;
  fileDetail: any;
  fileDetailCf: any;
  fileDetailCfFilteredVersions: any;
  fileDetailCfLoading: any;
  fileDetailCfMcOptions: any;
  fileDetailCfMcSel: any;
  fileDetailCfVersionBusy: any;
  fileDetailExternalUrl: any;
  fileDetailFilteredVersions: any;
  fileDetailInstalledVersion: any;
  fileDetailLoaderOptions: any;
  fileDetailLoaderSel: any;
  fileDetailMcOptions: any;
  fileDetailMcSel: any;
  fileDetailMr: any;
  fileDetailMrLoading: any;
  fileDetailMrVersionBusy: any;
  fileDetailMrVersions: any;
  fileDetailTab: any;
  fileDetailTabs: any;
  fileDetailTitle: any;
  fileDetailTypeSel: any;
  fileIcons: any;
  fileListFiltered: any;
  fileListRef: any;
  fileListScroll: any;
  fileListStart: any;
  fileListTotal: any;
  fileListVisible: any;
  fileMenuOpen: any;
  fileMenuRef: any;
  fileMetaTitle: any;
  filePercent: ComputedRef<any>;
  fileRowStride: any;
  fileSearch: Ref<any>;
  fileSortDir: any;
  fileSortKey: any;
  fileStatusFilter: any;
  fileToggling: any;
  fileVisibleCount: any;
  filesDone: Ref<any>;
  filteredCreateReleases: any;
  filteredCreateSnapshots: any;
  filteredModVersions: any;
  filteredNews: ComputedRef<any>;
  filteredPacks: any;
  formatBytes: (...args: any[]) => any;
  formatDate: (...args: any[]) => any;
  formatPlaytime: (...args: any[]) => any;
  formatPlaytimeShort: any;
  formatUnixDate: (...args: any[]) => any;
  gameFileIcon: any;
  gameFiles: any;
  gameRunning: Ref<any>;
  getLocaleMeta: any;
  handleAddPack: (...args: any[]) => any;
  handleClearLog: (...args: any[]) => any;
  handleCopyLog: (...args: any[]) => any;
  handleEly: (...args: any[]) => any;
  handleInstall: (...args: any[]) => any;
  handleMicrosoft: (...args: any[]) => any;
  handleMonoConfirmEmail: (...args: any[]) => any;
  handleMonoForgot: (...args: any[]) => any;
  handleMonoLogin: (...args: any[]) => any;
  handleMonoLogout: (...args: any[]) => any;
  handleMonoRegister: (...args: any[]) => any;
  handleMonoReset: (...args: any[]) => any;
  handleOffline: (...args: any[]) => any;
  handleOpenPackDir: (...args: any[]) => any;
  handlePlay: (...args: any[]) => any;
  handleRemoveAccount: (...args: any[]) => any;
  handleRemovePack: (...args: any[]) => any;
  handleSelectVersion: (...args: any[]) => any;
  handleStop: (...args: any[]) => any;
  handleSwitchAccount: (...args: any[]) => any;
  handleToggleFile: (...args: any[]) => any;
  handleUpdate: (...args: any[]) => any;
  handleVerify: (...args: any[]) => any;
  importAuthorPack: (...args: any[]) => any;
  installAppUpdate: (...args: any[]) => any;
  installCpPack: any;
  installCurse: any;
  curseDetail: any;
  curseDetailTab: any;
  curseVersions: any;
  openCurseDetail: any;
  closeCurseDetail: any;
  installFileDetailCfVersion: any;
  installFileDetailVersion: any;
  installModVersion: any;
  installNews: any;
  installPackVersion: any;
  installRemoteVersion: (...args: any[]) => any;
  installedCurseIds: any;
  installedModrinthSlugs: any;
  isActiveNewsTag: any;
  isAdmin: Ref<any>;
  isFileDetailWin: any;
  isFileSelected: any;
  isFileToggling: any;
  isInstalledVersion: (...args: any[]) => any;
  isMonoPackAdded: any;
  isNewsExpandable: any;
  isNewsExpanded: any;
  isSearchWin: any;
  javaArchLabel: any;
  javaBusy: Ref<any>;
  javaList: Ref<JavaInfo[]>;
  javaMsg: Ref<any>;
  javaSelected: Ref<string>;
  jvmArgs: any;
  jvmArgsSaving: any;
  keepOne: any;
  launcherVer: Ref<any>;
  libCatModal: any;
  libCatName: any;
  libCats: any;
  libCopyLink: any;
  libDoPlay: any;
  libMenuPack: any;
  libMenuPos: any;
  libOpenSettings: any;
  libPercent: any;
  libQuery: any;
  libScale: any;
  libStatus: any;
  libTile: any;
  licenseBusy: Ref<any>;
  licenseBusyFor: Ref<string | null>;
  licenseByPack: any;
  licenseError: Ref<any>;
  licenseInfo: Ref<LicenseInfo | null>;
  licenseKeyInput: Ref<any>;
  load: (...args: any[]) => any;
  loadAccounts: (...args: any[]) => any;
  loadAdminData: (...args: any[]) => any;
  loadAllLicenses: (...args: any[]) => any;
  loadAuthorNews: (...args: any[]) => any;
  loadAuthorPacks: (...args: any[]) => any;
  loadBoostyGlobal: (...args: any[]) => any;
  loadCatalogComments: (...args: any[]) => any;
  loadCollaborators: (...args: any[]) => any;
  loadDuplicates: (...args: any[]) => any;
  loadGameFiles: (...args: any[]) => any;
  loadJava: (...args: any[]) => any;
  loadLibraryStatus: any;
  loadLicenseStatus: (...args: any[]) => any;
  loadLicenseStatusFor: (...args: any[]) => any;
  loadLocalSkin: (...args: any[]) => any;
  loadMonoCatalog: (...args: any[]) => any;
  loadMoreMods: any;
  loadMyServers: (...args: any[]) => any;
  loadNews: (...args: any[]) => any;
  loadPackScreenshots: (...args: any[]) => any;
  loadPacks: (...args: any[]) => any;
  loaderLabel: ComputedRef<any>;
  loaderOptions: any;
  localSkin: Ref<SkinInfo | null>;
  locale: any;
  localeLabel: any;
  locales: any;
  logEntries: Ref<LaunchLogEntry[]>;
  logRef: Ref<HTMLElement | null>;
  loginBusy: any;
  loginError: any;
  loginLogin: any;
  loginMethod: any;
  loginOpen: any;
  loginPassword: any;
  loginPasswordVisible: any;
  makeCatId: any;
  maxRam: Ref<any>;
  modDatapackWorldSel: any;
  modDetail: any;
  modDetailTab: any;
  modDetailTabs: any;
  modEnvSel: any;
  modFilters: any;
  modFiltersActive: any;
  modInstallBusy: any;
  modPackDetail: any;
  modPackInstalling: any;
  modPackLoading: any;
  modPackOpen: any;
  modPackQuery: any;
  modPackResults: any;
  modPackService: any;
  modPackTab: any;
  modPackTabs: any;
  modPackVersions: any;
  modSearchBox: any;
  modSearchErr: any;
  modSearchKind: any;
  modSearchLoading: any;
  modSearchMore: any;
  modSearchMoreBusy: any;
  modSearchQuery: any;
  modSearchResults: any;
  modSortSel: any;
  modUpdateFor: any;
  modUpdatesTab: any;
  modVersionTypeSel: any;
  modVersions: any;
  modVersionsRaw: any;
  modrinthMetaFor: any;
  modrinthVersionFor: any;
  monoAuthBusy: Ref<any>;
  monoBusy: Ref<any>;
  monoCatalog: Ref<PackCatalog[]>;
  monoCatalogError: Ref<any>;
  monoCatalogLoading: Ref<any>;
  monoForgotEmail: Ref<any>;
  monoForgotOpen: Ref<any>;
  monoForgotSent: Ref<any>;
  monoName: Ref<any>;
  monoPass: Ref<any>;
  monoProfile: Ref<MonoProfile | null>;
  monoResetDone: Ref<any>;
  monoResetPass: Ref<any>;
  monoResetToken: Ref<any>;
  moveAuthorShot: any;
  msFlow: Ref<MsDeviceCodeInfo | null>;
  msPolling: Ref<any>;
  multiSelBusy: any;
  myServers: Ref<SavedServer[]>;
  myServersInstalled: Ref<any>;
  news: Ref<NewsItem[] | null>;
  newsFilter: Ref<string>;
  newsSources: ComputedRef<any>;
  notifications: Ref<Notice[]>;
  notify: (...args: any[]) => any;
  onChangelogLinkClick: any;
  onJavaChange: any;
  onSidebarDrag: any;
  openAuthorDetail: (...args: any[]) => any;
  openAuthorExport: any;
  openBugReportIssue: (...args: any[]) => any;
  openCatCreate: any;
  openCatRename: any;
  openCatalogCurseDetail: any;
  openCatalogDetail: (...args: any[]) => any;
  openCatalogModrinthDetail: any;
  openCatalogPackById: any;
  openCpFiles: any;
  openCrashIssue: any;
  openEditVersion: any;
  openExampleInLauncher: any;
  openExamplePack: any;
  openExport: any;
  openExternal: any;
  openFileDetail: any;
  openFileOnCurseForge: (...args: any[]) => any;
  openFileOnModrinth: (...args: any[]) => any;
  openFolder: (...args: any[]) => any;
  openLibMenu: any;
  openModDetail: any;
  openModPackModal: any;
  openModScanner: any;
  openMonoPack: any;
  openMsAuthPage: (...args: any[]) => any;
  openNewsLink: any;
  openPackDetail: any;
  openPackTab: any;
  openProfileView: (...args: any[]) => any;
  openSearch: any;
  openSelected: any;
  packCategoryOptions: any;
  packEnvSel: any;
  packFilters: any;
  packHasCat: any;
  packId: Ref<any>;
  packLibCats: any;
  packLoaderOptions: any;
  packLocked: Ref<any>;
  packName: Ref<any>;
  packNameFor: any;
  packScreenshots: Ref<ScreenshotInfo[]>;
  packScreenshotsInstalled: Ref<any>;
  packSortSel: any;
  packThemeActive: any;
  packUrl: Ref<any>;
  packVersionOptions: any;
  packVersionTypeSel: any;
  packs: Ref<PackDescriptor[]>;
  packsBySource: any;
  paidPacks: any;
  percent: ComputedRef<any>;
  phaseLabel: any;
  pickAndScanJar: any;
  pickAuthorImportFile: any;
  pickAuthorShotFile: any;
  pickAuthorVersionFile: any;
  pickCreateFile: any;
  pickPackBanner: any;
  pickPackIcon: any;
  playLibraryPack: any;
  playOnServer: (...args: any[]) => any;
  playSubTab: Ref<"releases" | "mods" | "resourcepacks" | "shaderpacks" | "duplicates" | "saves" | "screenshots" | "servers" | "console" | "settings">;
  playSubTabsVisible: any;
  profileBioDraft: any;
  profileBioEditing: any;
  profileBusy: Ref<any>;
  profileIsOwn: ComputedRef<any>;
  profileView: Ref<ProfileDetail | null>;
  progress: Ref<ProgressState | null>;
  quickDownloadMod: any;
  quickDownloadPack: any;
  quickModBusy: any;
  quickPackBusy: any;
  ram: Ref<any>;
  rateCatalogComment: (...args: any[]) => any;
  ratePack: (...args: any[]) => any;
  refreshRemoteVersions: (...args: any[]) => any;
  refreshSkin: (...args: any[]) => any;
  refreshVersions: (...args: any[]) => any;
  remoteInstallingId: Ref<string | null>;
  remoteVersions: Ref<PackVersionPublic[] | null>;
  remoteVersionsLoading: Ref<any>;
  removeArmed: Ref<string | null>;
  removeAuthorServer: any;
  removeAuthorShot: any;
  removeAuthorSocial: any;
  removeCatalogComment: (...args: any[]) => any;
  removeCollaborator: (...args: any[]) => any;
  removeDuplicate: (...args: any[]) => any;
  removeLicense: (...args: any[]) => any;
  removeLicenseFor: (...args: any[]) => any;
  removeLocalSkin: (...args: any[]) => any;
  removingPack: Ref<any>;
  renameLibCat: any;
  renderInline: any;
  reportError: (...args: any[]) => any;
  reportPackBug: (...args: any[]) => any;
  resetAuthorForm: any;
  resetModFiltersAndSearch: any;
  resetRemoveArm: (...args: any[]) => any;
  runCrashAnalysis: (...args: any[]) => any;
  saveAuthorOverview: any;
  saveBoostyGlobal: (...args: any[]) => any;
  saveEditVersion: any;
  saveJvmArgs: any;
  saveLicense: (...args: any[]) => any;
  saveLicenseFor: (...args: any[]) => any;
  saveMyProfile: (...args: any[]) => any;
  scanActiveCustomMods: (...args: any[]) => any;
  scanBusy: Ref<any>;
  scanByHash: (...args: any[]) => any;
  scanModFile: (...args: any[]) => any;
  scanResult: Ref<ScanResult | null>;
  scannerHash: any;
  scannerOpen: any;
  screenshotsLoading: Ref<any>;
  searchCurse: any;
  searchCursePacks: any;
  searchIconUrl: any;
  searchInput: any;
  searchLoading: any;
  searchMods: any;
  searchOpen: any;
  searchPacks: any;
  searchPacksOrCurse: any;
  searchService: any;
  searchTitle: any;
  searchWinStyle: any;
  selCurse: any;
  selModrinth: any;
  selectAllFiles: (...args: any[]) => any;
  selectJava: (...args: any[]) => any;
  selectPack: (...args: any[]) => any;
  selectedFiles: any;
  sendCatalogComment: (...args: any[]) => any;
  serverGroups: any;
  serverKey: any;
  serverPlayersOf: any;
  serverStateOf: any;
  serverStatusText: any;
  serverStatuses: any;
  session: Ref<UserSession | null>;
  setActivePackLocked: (...args: any[]) => any;
  setFileStatusFilter: any;
  setLibScale: any;
  setLocale: any;
  setPackThemeVars: any;
  setSelectedFilesEnabled: (...args: any[]) => any;
  setShotCaption: any;
  setThemeLevel: any;
  shotIdx: any;
  sidebarCat: any;
  sidebarCollapsed: any;
  sidebarDragging: any;
  sidebarRecentPacks: any;
  sidebarWidth: any;
  skinApi: Ref<any>;
  skinBusy: Ref<any>;
  skinModel: Ref<"classic" | "slim">;
  skinUrl: Ref<any>;
  sortSelectOptions: any;
  startBoostyGlobalLogin: (...args: any[]) => any;
  startBoostyLogin: (...args: any[]) => any;
  startSidebarDrag: any;
  status: Ref<AppStatus | null>;
  subTabCount: any;
  submitAuthorVersion: any;
  submitCatModal: any;
  switchCatalogSource: any;
  switchPackService: any;
  switchSearchService: any;
  systemRam: Ref<SystemInfo | null>;
  t: any;
  tab: Ref<"play" | "settings" | "news" | "catalog" | "dev" | "library" | "author" | "admin">;
  takeAuthorFormBase: (...args: any[]) => any;
  themeLevel: any;
  themePreview: any;
  toggleAutostart: any;
  toggleCloseToTray: any;
  toggleCurseSel: any;
  toggleDiscordRp: (...args: any[]) => any;
  toggleExport: any;
  toggleExportAll: any;
  toggleExportExpand: any;
  toggleFileSelect: (...args: any[]) => any;
  toggleFileSort: any;
  toggleModrinthSel: any;
  toggleNewsExpanded: any;
  togglePackCat: any;
  toggleSidebarCat: any;
  toggleTheme: any;
  toggleWarnCustomMods: (...args: any[]) => any;
  unbindArmed: any;
  unlinkBoostyGlobal: (...args: any[]) => any;
  updateAllBusy: any;
  updateAllMods: any;
  updateAuthorMeta: (...args: any[]) => any;
  updateCollaborator: (...args: any[]) => any;
  updateFileDetail: any;
  updateInfo: Ref<UpdateInfo | null>;
  updateOneMod: any;
  updatingFileDetail: any;
  updatingMod: any;
  uploadAuthorScreenshot: (...args: any[]) => any;
  username: Ref<any>;
  verFilterLoaderOptions: any;
  verFilterLoaderSel: any;
  verFilterMcOptions: any;
  verFilterMcSel: any;
  verFilterTypeOptions: any;
  verFilterTypeSel: any;
  verInstallSize: any;
  verTypeColor: any;
  verifyBusy: Ref<any>;
  verifyResult: Ref<VerifyResult | null>;
  versionOptions: any;
  versionTypeOptions: any;
  versions: Ref<VersionsInfo | null>;
  visibleNewsLines: any;
  warnCustomMods: Ref<any>;
  windowHeight: Ref<any>;
  windowWidth: Ref<any>;
  worldOptions: any;
}

export const LauncherCtxKey: InjectionKey<LauncherCtx> = Symbol("launcher-ctx");

export function useLauncherCtx(): LauncherCtx {
  return inject(LauncherCtxKey)!;
}

